Create onMounting hook
rumkin/pill pull request #6
Opened 2019-08-24 11:35 UTC by tamb

This hook fires before every content change.  This way we can clean up any assets we may want to clean up before content changes.

2019-09-01 10:16 UTC, rumkin commented
Just have reviewed the PR. Currently it has conflicts. Could you clean it up and remove anything not related to the changed behavior itself?

2019-09-01 10:21 UTC, rumkin requested changes

2019-09-01 10:21 UTC, rumkin commented on src/pill.js
> +    if (e.target.nodeName !== 'A' && !e.target.dataset.pillIgnore) {
Should be removed, it has already landed in another PR.

2019-09-01 10:21 UTC, rumkin commented on readme.md
> +
It conflicts with already existing PR.

2019-09-01 10:21 UTC, rumkin commented on package.json
>      "clean": "rm -rf dist",
Presented in PR #10

2019-09-01 10:21 UTC, rumkin commented on copy-files.js
> +copy('dist/*.js', 'example', ()=> console.log('copied pill.js build into example'));
This part should be removed. It's presented in PR #10.

2019-09-01 10:21 UTC, rumkin commented on example/index.html
>      <script src='/site.js' type='module'></script>
Presented in PR #9

2019-09-01 10:21 UTC, rumkin commented on example/pages/a.html
>  </html>
Presented in PR #9

2019-09-01 10:21 UTC, rumkin commented on example/pages/b.html
>  </html>
Presented in PR #9

2019-09-01 10:21 UTC, rumkin commented on example/site.js
> +
Conflicts with PR #9

2019-09-02 20:29 UTC, tamb commented
@rumkin Question:  Should this be `onMounting` or `onLoading`.  And the fetching of the page is `onFetch`??  What naming would you want?

2019-09-02 20:59 UTC, closed without merging

2019-09-02 21:00 UTC, rumkin commented
@tamb Let's implement only `onMounting` hook in this PR. I have some doubts about onFetch interface.